const DEFAULT_VALUES = {
  DOMAIN: {
    BALANCE_UNIT: 1000,
    LOTTO_PRICE: 1000,
    MIN_LOTTO_VALUE: 1,
    MAX_LOTTO_VALUE: 45,
    LOTTO_NUMBER_COUNT: 6,
  },
};

export default DEFAULT_VALUES;
